name: Container Build

on:
  push:
    tags: ['*']
    branches: ['main']
    paths:
      - '.github/Dockerfile'
      - '.github/workflows/container.yml'
  pull_request:
    paths:
      - '.github/Dockerfile'
      - '.github/workflows/container.yml'
  workflow_run:
    workflows: [Build RISC-V Linux GLIBC Cross Compiler]
    types:
      - completed
  workflow_dispatch:

env:
  IMAGE_NAME: bergamot-build

jobs:
  container:
    name: container
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Download compiler
        uses: dawidd6/action-download-artifact@v21
        with:
          workflow: compiler.yml
          name: riscv-linux-rv32gc-ilp32
          path: ./riscv-toolchain
      - name: Build image
        run: docker build . --file .github/Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "main" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION