name: Continuous Integration

on:
  push:
    tags: ['*']
    branches: ['main']
  pull_request:

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/lovelonelytime/bergamot-build:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Compile
        run: make verilogsim
