name: Continuous Integration

on:
  push:
    tags: ['*']
    branches: ['main']
  pull_request:

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache Scala
        uses: coursier/cache-action@v8
      - name: Setup Scala
        uses: coursier/setup-action@v3
        with:
          jvm: adopt:11
          apps: sbt mill
      - name: Compile
        run: make verilogsim
