name: Continuous Integration

on:
  push:
    tags: ['*']
    branches: ['main']
  pull_request:

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/bergamot-build
    steps:
      - uses: actions/checkout@v6
      - name: Compile
        run: make verilogsim
